# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XDTableviewDemo' do
pod 'MJRefresh', '~> 3.1.15.7'  
pod 'Masonry', '~> 1.0.2'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XDTableviewDemo

  target 'XDTableviewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XDTableviewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
